apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-native-image
spec:
  workspaces:
    - name: source
  steps:
    - name: build-native-image-graalvm
      image: vijayakkineni/scala-sbt:graalvm-ce-22.3.1-java17_1.8.2_3.2.2
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        sbt "nativeImageRunAgent; nativeImage;"
        cat /workspace/source/target/native-image-configs/reflect-config.json
