apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scala3-learn-pipeline # The name of the pipeline
spec:
  workspaces:
    - name: scala3-learn-workspace # attach a volume to store source code
    - name: docker-credentials
  tasks:
    - name: fetch-repository # The name of the first task
      taskRef:
        name: git-clone # The task this pipeline should run first (git-clone task)
      workspaces:
        - name: output
          workspace: scala3-learn-workspace
      params:
        - name: url
          value: https://github.com/akkinenivijay/scala3-learn # The GitHub repository
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-app
      taskRef:
        name: build-app
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: scala3-learn-workspace
    - name: test-app
      taskRef:
        name: test-app
      runAfter:
        - build-app
      workspaces:
        - name: source
          workspace: scala3-learn-workspace
    - name: build-native-image
      taskRef:
        name: build-native-image
      runAfter:
        - test-app
      workspaces:
        - name: source
          workspace: scala3-learn-workspace
    - name: image-push
      runAfter: ["build-native-image"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: scala3-learn-workspace
      - name: dockerconfig
        workspace: docker-credentials
      params:
      - name: IMAGE
        value: vijayakkineni/scala3learn:latest
          